const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94766372136"
const SESSION_ID = "PRABATH-MD~SX5UjCZR#Hw_nkogi7n1SWF9_Swe9M2xnxGy8prUuPYAnG9XQcgs"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
