const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94766372136"
const SESSION_ID = "PRABATH-MD~uTYRTRKD#brRcd-e3EWt56w7xa858V7iEoL4-GmVdEt1hUXou6aM"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
